#ifndef CHEATS_H
#define CHEATS_H
#include "plugin.h"
void	Car(void);
void	Dog(void);
void	Bike(void);
void	Xenom1(void);
void	Xenom2(void);
void	Xenom4(void);
void	Xenom7(void);
void	Xenom8(void);
void	Xenom9(void);
void	Xenom10(void);
void	Xenom11(void);
void	Xenom12(void);
void	Xenom13(void);
void	Xenom14(void);
void	Xenom15(void);
void	Xenom16(void);
void	Xenom17(void);
void	Xenom18(void);
void	Xenom19(void);
void	Xenom20(void);
void	Xenom24(void);
void	Xenom26(void);
void	Xenom27(void);
void	Xenom29(void);
void	Xenom30(void);
void	Xenom31(void);
void	Xenom35(void);
void	Xenom36(void);
void	Xenom37(void);
void	Xenom38(void);
void	Xenom39(void);
void	Xenom40(void);
void	Xenom41(void);
void	Xenom43(void);
void	Xenom44(void);
void	Xenom45(void);
void	Xenom46(void);
void	Xenom47(void);
void	Xenom48(void);
#endif
